- name: demo on secret variables
  hosts: localhost
  connection: local
  vars_prompt:
    - name: username
      prompt: "enter username"
      private: false

    - name: password
      prompt: "enter password"
      private: true

  tasks:
   - name: print the values
     debug:
       msg: "user name is {{username}} and password is {{password}}"