- name: course information
  hosts: local
  connection: local
  vars:
    course: "DevSecOps with AIOPS" # String
    duration_in_hrs: 150 # int/number
    is_live_sessions: true # bool
    topics: # list
    - linux
    - shell
    - ansible
    more_details: # map
     months: "5"
     trainer: "siva"

  tasks:
   - name: 
      debug:
       msg: |
        name: {{ course }}
        duration: {{ duration_in_hrs }}
        is_live_sessions: {{ is_live_sessions }}
        topics: {{ topics }}
        more_details: {{ more_details }}
        