- name: check number of live is_live_sessions
  hosts: local
  connection: local
  vars:
    is_live_sessions: 6
  tasks:
   - name: is number of live sessions for ansible is greater than 5
     debug:
       msg: "yes, number of live sessions for ansible is greater than 5"
     when: is_live_sessions > 5  