- name: demo on filters
  hosts: frontend
  connection: local
  vars:
    topics: Linux, Shell, Ansible, Terraform
  tasks:
  - name: convert string to list
    debug:
      msg: "topics are ... {{ topics | split(',') }}"

  - name: set default values
    debug:
      msg: "Hi {{ Greeting | default(' Hello Sir')}}"