[frontend]
; 172.31.31.89  COURSE="Ansible Node-1 Course"
; 172.31.20.148 COURSE="Ansible Node-2 Course"
172.31.24.96 COURSE="Hello Ansible Node-3 Course"

[local]
localhost

[local:vars]
COURSE= "DevOps with AWS"
TRAINER= "Siva"
DURATION= "100 HRS"

[frontend:vars]
COURSE= "DevOps Engineer Course"
TRAINER= "DevOps Siva"
DURATION= "101 HRS"