[frontend]
172.31.24.96 COURSE="Ansible Node-3 DevOps Course"
172.31.31.89 COURSE="Ansible Node-1 DevOps Course"
172.31.20.148 COURSE="Ansible Node-2 DevOps Course"
[frontend:vars]
COURSE="DevOps Engineer Course"
TRAINER="DevOps Siva"
DURATION="101 HRS"